apiVersion: v1
kind: Service
metadata:
  name: flask-app
  namespace: flask-app
  labels:
    app.kubernetes.io/name: flask-app
    app.kubernetes.io/part-of: devops-project-2
    environment: dev
spec:
  type: ClusterIP # Using this type for internal communication until I configure an Ingress controller and AWS ALB.
  selector:
    app.kubernetes.io/name: flask-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http