name: Deploy Flask Application

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-central-1
  EKS_CLUSTER_NAME: devops-project-2
  KUBERNETES_NAMESPACE: flask-app
  KUBERNETES_SECRET_NAME: flask-app-secret
  DEPLOYMENT_NAME: flask-app
  SERVICE_NAME: flask-app

jobs:
    deploy:
        name: Deploy Flask Application to EKS
        runs-on: ubuntu-latest
        timeout-minutes: 15 # A timeout of 15 minutes to prevent long-running deployments

        # Running the deployment job only on the main branch
        if: github.ref == 'refs/heads/main'

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                role-to-assume: arn:aws:iam::215229808174:role/devops-project-2-dev-github-actions-role
                role-session-name: github-actions-deploy-app
                aws-region: ${{ env.AWS_REGION }}
            
            - name: Configure kubectl
              run: |
                aws eks update-kubeconfig \
                --region "$AWS_REGION" \
                --name "$EKS_CLUSTER_NAME"

            - name: Verify Kubernetes permissions
              run: |
                for permission in \
                    "get configmaps" \
                    "create configmaps" \
                    "patch configmaps" \
                    "get secrets" \
                    "create secrets" \
                    "patch secrets" \
                    "get deployments.apps" \
                    "create deployments.apps" \
                    "patch deployments.apps" \
                    "get services" \
                    "create services" \
                    "patch services" \
                    "get endpointslices.discovery.k8s.io"
                  do
                    verb="${permission%% *}"
                    resource="${permission#* }"

                    result="$(
                      kubectl auth can-i "$verb" "$resource" \
                        --namespace "$KUBERNETES_NAMESPACE"
                    )"

                    if [ "$result" != "yes" ]; then
                      echo "Missing permission: $verb $resource"
                      exit 1
                    fi
                  done

            - name: Validate APP_SECRET
              env:
                APP_SECRET: ${{ secrets.APP_SECRET }}
              run: |
                if [ -z "$APP_SECRET" ]; then
                  echo "Error: APP_SECRET is not set. Please set the APP_SECRET."
                  exit 1
                fi

            - name: Apply ConfigMap
              run: |
                kubectl apply -f k8s/base/configmap.yaml

            - name: Create or update k8s Secret
              env:
                APP_SECRET: ${{ secrets.APP_SECRET }}
              run: |
                kubectl create secret generic "$KUBERNETES_SECRET_NAME" \
                --namespace "$KUBERNETES_NAMESPACE" \
                --from-literal=APP_SECRET="$APP_SECRET" \
                --dry-run=client \
                --output=yaml | kubectl apply -f -

            - name: Apply app's resources (Deployment and Service)
              run: |
                kubectl apply -f k8s/base/deployment.yaml
                kubectl apply -f k8s/base/service.yaml

            - name: Verify Deployment
              run: |
                kubectl rollout status deployment "$DEPLOYMENT_NAME" \
                --namespace "$KUBERNETES_NAMESPACE"
                --timeout=5m

            - name: Verify app's resource (Deployment and Service)
              run: |
                kubectl get deployment "$DEPLOYMENT_NAME" \
                --namespace "$KUBERNETES_NAMESPACE"

                kubectl get service "$SERVICE_NAME" \
                --namespace "$KUBERNETES_NAMESPACE"

                kubectl get pods \
                --namespace "$KUBERNETES_NAMESPACE" \
                --selector app.kubernetes.io/name=flask-app \
                --output=wide

                kubectl get endpointslices \
                --namespace "$KUBERNETES_NAMESPACE" \
                --selector kubernetes.io/service-name="$SERVICE_NAME"

            - name: Verify Kubernetes Secret
              run: |
                test -n "$(
                    kubectl get secret "$KUBERNETES_SECRET_NAME" \
                    --namespace "$KUBERNETES_NAMESPACE" \
                    --output=jsonpath='{.data.APP_SECRET}'
                )"

                echo "Application deployment completed successfully."